### PR TITLE
Add SonarCloud.io

### PR DESCRIPTION
**Pull request by Ingvord**
SonarCube hosted on sonarcloud.io seems to be much better alternative(addition) to codacy.

Result of the analysis of this branch can be found [here](https://sonarcloud.io/project/issues?branch=integrate-sonar&id=org.tango-controls%3Acpp-tango%3Atango-9-lts&resolved=false)

### CODE REVIEW

**Comment by Ingvord** [comment]
@bourtemb , yes, you are absolutely right! That would be further improvement. We just need to figure out how to integrate build-wrapper into our dockers (which BTW would be nice to replace with native Travis images if possible). Anyway at this point it is already a good result, and I like the result of the analysis.

**Comment by bourtemb** [comment]
I understand...
Can we add a sonarcloud badge to the README too?

**Comment by Ingvord** [comment]
@bourtemb , sure! Once we merge it and run analysis on the tango-9-lts branch we can add sonar metrics to readme, like in JTango's [readme](https://github.com/tango-controls/JTango#sonarcloud)

**Comment by Ingvord** [comment]
@bourtemb , build-wrapper is added in fbc9707

**Pull request merged**
