### PR TITLE
Fix sonar scanner invocation

### LINKED ISSUE #661: Fix Coveralls and Sonar configuration
Coveralls and Sonar integration was disabled in 226d70c and then re-enabled in 890fd59. Seems that it no longer works correctly. Original report: https://github.com/tango-controls/cppTango/pull/607#issuecomment-577145224

https://travis-ci.org/tango-controls/cppTango/jobs/640430653?utm_medium=notification&utm_source=github_status

Coveralls:
```
[  0%] Built target coveralls_generate
make -f CMakeFiles/coveralls_upload.dir/build.make CMakeFiles/coveralls_upload.dir/depend
make[3]: Entering directory '/home/tango/src/build'
cd /home/tango/src/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/tango/src /home/tango/src /home/tango/src/build /home/tango/src/build /home/tango/src/build/CMakeFiles/coveralls_upload.dir/DependInfo.cmake --color=
Scanning dependencies of target coveralls_upload
make[3]: Leaving directory '/home/tango/src/build'
make -f CMakeFiles/coveralls_upload.dir/build.make CMakeFiles/coveralls_upload.dir/build
make[3]: Entering directory '/home/tango/src/build'
/usr/bin/cmake -E cmake_progress_report /home/tango/src/build/CMakeFiles 34
[100%] Uploading coveralls output...
/usr/bin/curl -S -F json_file=@/home/tango/src/build/coveralls.json https://coveralls.io/api/v1/jobs
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 15 1031k    0     0   15  160k      0  1260k --:--:-- --:--:-- --:--:-- 1261k
100 1031k    0    72  100 1031k     54   774k  0:00:01  0:00:01 --:--:--  773k
100 1031k    0    72  100 1031k     54   774k  0:00:01  0:00:01 --:--:--  773k
{"message":"Couldn't find a repository matching this job.","error":true}make[3]: Leaving directory '/home/tango/src/build'
```

Coverage is not visible: https://coveralls.io/github/tango-controls/cppTango

Sonar:
```
[0K$ test ${SONAR_SCANNER} = "ON" && .travis/sonar.sh
Using SONAR_PROPERTIES=-Dsonar.pullrequest.base=tango-9-lts -Dsonar.pullrequest.branch=reset-database-and-ds-for-each-test -Dsonar.pullrequest.key=640
.travis/sonar.sh: line 11: sonar-scanner: command not found
```

### LINKED ISSUE #710: Travis CI potential optimization: No need to clone and install tango_admin when RUN_TESTS=OFF
When RUN_TESTS is set to OFF, there is no need for the Travis jobs to clone and install tango_admin.

### PR DESCRIPTION
**Pull request by t-b**
- [x] Fix sonarcloud
- [x] Fix coveralls

Close #661.

### CODE REVIEW

**Comment by t-b** [comment]
@bourtemb Can you send me the repo token from https://coveralls.io/github/tango-controls/cppTango (found at the bottom) in a private message? I need that to set in travis but only admins on tango-controls/cppTango can see that.

**Comment by t-b** [comment]
See https://coveralls.io/builds/31751625 for the coveralls result.

**Review by mliszcz — COMMENTED** [review]
LGTM, thanks for this PR!

I have just few suggestions:
* we have this file `configure/coveralls.cmake`. Consider adding *.tpp files as well:
   ```
       FILE(GLOB_RECURSE COVERAGE_SRCS ${PROJECT_SOURCE_DIR}/cppapi/*.cpp ${PROJECT_SOURCE_DIR}/cppapi/*.h)
   ```
* We compile cppTango and run the tests twice (first for coveralls and then for sonar) and job run time is over 40 minutes now. I propose:
   * either move coveralls to another job so they can run in parallel
   * or remove coveralls completely (we have coverage calculated by sonar as well)
   * or temporary disable coveralls and see what can be done to run the tests just once and reuse gcov files.
* The tests failed during coveralls run (usual unstable tests issue) but still we generated the report and job is marked as passed.
   * https://travis-ci.org/github/tango-controls/cppTango/jobs/698710210
   ```
    99% tests passed, 1 tests failed out of 94
    Total Test time (real) = 745.23 sec
    The following tests FAILED:
            80 - event::change_event (Failed)
   ```
   * I think nothing can be done as this is just how the coveralls plugin works: https://github.com/JoakimSoderberg/coveralls-cmake/blob/master/cmake/Coveralls.cmake#L63-L74
   * What we can do is to disable coveralls for now (not to hide any failures in Debian 8 tests) and look for another plugin in a separate PR.

**Comment by t-b** [comment]
@mliszcz 
Thanks for the review.

- I've fixed `configure/coveralls.cmake` as per your suggestion.
- I've removed some more old clutter
- The long running time of the job is due to me restarting it manually IIRC. Same for it not failing properly. But let's see what the next run gives.

**Comment by t-b** [comment]
@mliszcz https://travis-ci.org/github/tango-controls/cppTango/jobs/706083973 shows that it properly fails. If you now restart the job it looks like the job runs much longer.

**Review by mliszcz — APPROVED** [review]
@t-b indeed fails as expected now. LGTM, thanks!

**Comment by t-b** [comment]
@bourtemb Could you have a look? Thanks.

**Review by bourtemb — APPROVED** [review]
Thanks for repairing that, @t-b.
LGTM

**Pull request merged**
