### PR TITLE
Fix misleading-indentation warning for GCC 6.0 and higher

### PR DESCRIPTION
**Pull request by t-b**
A more future proof fix would probably be to add a .clang-format definition and a `make format` target calling `clang-format`.

### CODE REVIEW

**Comment by Ingvord** [comment]
Is this 4 spaces indentation?

**Comment by t-b** [comment]
@Ingvord It's tab like the surrounding code.

**Comment by Ingvord** [comment]
@t-b we are migrating to 4 spaces. Could you please confirm that this is OK for GCC 6.0 as well?

**Comment by t-b** [comment]
@Ingvord Yes still works when I convert the whole file via `sed -i  's/\t/    /g' attribute.tpp` to four spaces..

**Comment by t-b** [comment]
@Ingvord thanks.

**Pull request merged**
