### PR TITLE
Tango 9 lts remove zmq hpp

### PR DESCRIPTION
**Pull request by bourtemb**
Remove zmq.hpp from tango-9-lts (#266)
Add CPPZMQ_BASE CMake optional variable

### CODE REVIEW

**Comment by t-b** [comment]
@bourtemb Is cppzmq now a required dependecy? If yes cmake should also complain if it could not be found or?

**Comment by bourtemb** [comment]
Well, zmq.hpp file is required.
On Debian it is distributed with zmq Debian packages.
On some other platforms, it might be independent.
Maybe we should add a [CHECK_INCLUDE_FILE](https://cmake.org/cmake/help/v3.0/module/CheckIncludeFile.html) line to ensure it is available on the system and give a nice message explaining this requirement if the file is not found....

**Comment by t-b** [comment]
> Maybe we should add a CHECK_INCLUDE_FILE line to ensure it is available on the system and give a 
> nice message explaining this requirement if the file is not found....

yes that sounds good!

**Comment by t-b** [comment]
@bourtemb THanks, I've just tested it here locally and it works.

**Comment by bourtemb** [comment]
@t-b Thank you very much for your feedback and for having taken the time to test it.

**Comment by bourtemb** [comment]
Closing this PR since it is now handled by PR #421

**Pull request closed without merging**
