### PR TITLE
Add CHANGELOG.md

### PR DESCRIPTION
**Pull request by bourtemb**
based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)
Add more details about changes occurring since Tango 9.2.5 and potential impact on user experience as suggested by #509

### CODE REVIEW

**Comment by bourtemb** [comment]
RELEASE_NOTES file is kept for the moment but should probably be replaced with something less technical and giving a better summary of the main changes, asking users to refer to the CHANGELOG.md file if they want more technical details.
I think release notes should also focus on the changes between stable releases.
The user does not care if a bug was introduced in 9.2.9 and fixed in 9.3.3 if this bug was not present in 9.2.5.
We could actually create a wiki page for the Release Notes when there will be a new stable release to have them in a more friendly format where we could eventually insert snapshots and images.

**Comment by bourtemb** [comment]
I propose to go ahead and to do a cppTango 9.3.3 release, flagged as pre-release on Github.
Before to tag this new version, I'd like to merge this Pull Request listing all the changes.
The exact date of the release will have to be updated on CHANGELOG.md and RELEASE_NOTES.md when we will create the release.

**Comment by Ingvord** [comment]
> We could actually create a wiki page for the Release Notes when there will be a new stable release to have them in a more friendly format where we could eventually insert snapshots and images.

IMHO we should use GitHub releases for RELEASE_NOTES. Seems more logical for me than a dedicated wiki page. When you go to releases it lists all the releases with some details as in [Waltz](https://github.com/tango-controls/waltz/releases) for instance.

**Comment by bourtemb** [comment]
> IMHO we should use GitHub releases for RELEASE_NOTES. Seems more logical for me than a dedicated wiki page. When you go to releases it lists all the releases with some details as in [Waltz](https://github.com/tango-controls/waltz/releases) for instance.

The release notes should be on the Github release page I agree with you. And your example with Waltz shows that there is no problem to include images if needed on this Github release page.

**Comment by bourtemb** [comment]
@ingvord, thanks for your review.
I added 5 small commits since you last reviewed this PR.
Could you please review again this PR and if you agree, could you please merge it?
I'd like to tag the release tomorrow (Friday 29).
As I already wrote about the RELEASE_NOTES file, IMHO it is good to keep it as a file provided with the source code too. And it's easier to proceed like that when preparing the release so we can prepare and discuss the contents of the release notes in a Pull Request.
I agree with you when you write "it should be on the Github release page".
I simply propose to copy the content of this file in the Github release page when the release is created.

**Pull request merged**
