### PR TITLE
See if we can use dist:trusty in Travis

### PR DESCRIPTION
**Pull request by Ingvord**
Following #562 discussion

### CODE REVIEW

**Comment by Ingvord** [comment]
This seems to help (from Travis log):

```
INFO: ANALYSIS SUCCESSFUL, you can browse https://sonarcloud.io/dashboard?id=org.tango-controls%3Acpp-tango%3Atango-9-lts&branch=Ingvord-change-travis-dist&resolved=false
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at https://sonarcloud.io/api/ce/task?id=AWxOp5AuhvfIjRvd_cuH
INFO: Analysis total time: 3:14.103 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 3:41.212s
INFO: Final Memory: 31M/393M
INFO: ------------------------------------------------------------------------
```

And there is activity related for today: [link](https://sonarcloud.io/project/activity?id=org.tango-controls%3Acpp-tango%3Atango-9-lts&selected_date=2019-08-01T12%3A30%3A30%2B0000)

Frankly speaking for `tango-9-lts` branch it worked on xenial as well, see, for instance [this build](https://travis-ci.org/tango-controls/cppTango/jobs/566415408)

**Comment by t-b** [comment]
@Ingvord Nice! I've taken the liberty to remove the bogus commits.

**Comment by bourtemb** [comment]
> Frankly speaking for `tango-9-lts` branch it worked on xenial as well, see, for instance [this build](https://travis-ci.org/tango-controls/cppTango/jobs/566415408)

I would prefer to stay on xenial (if it still works there as suggested by @Ingvord ) because Travis Trusty has already reached the end of standard support. xenial is currently the Travis default Linux Environment.

**Comment by t-b** [comment]
Yes, that works with xenial as well. See https://travis-ci.org/tango-controls/cppTango/jobs/600784825. I'll close that PR for now then. Feel free to reopen.

**Pull request closed without merging**
