### PR TITLE
Fix race conditions between polling threads and user threads pushing events

### PR DESCRIPTION
**Pull request by mliszcz**
Changes proposed in comment in another PR: https://github.com/tango-controls/cppTango/pull/635#issuecomment-565041260

### CODE REVIEW

**Comment by mliszcz** [comment]
Hi @gscalamera and @lorenzopivetta. This is PR which should correct #511. It contains necessary changes extracted from #635 and refactored. Could you please try to apply this patch and see if it solves the crash in your environment?

**Comment by mliszcz** [comment]
Thanks a lot Thomas for a detailed review and analysis!
I propose to leave this PR as it is, as it targets the development branch and if backport to 9.3-compatible version is needed, I'll restore the `detect_mutex` and remove function from `LastAttrValue` (it's just refactoring). What do you think?

**Comment by t-b** [comment]
@mliszcz Sounds good.

**Comment by lorenzopivetta** [comment]
> Hi @gscalamera and @lorenzopivetta. This is PR which should correct #511. It contains necessary changes extracted from #635 and refactored. Could you please try to apply this patch and see if it solves the crash in your environment?

Hi @mliszcz . Applied to 9-lts branch and compiled on PPC (requires tricking some configs). Need to wait for @gscalamera for testing.

**Comment by bourtemb** [comment]
We encountered the same issue #511 in one of our device servers here at the ESRF which was crashing several times a day.
We are currently testing this patch since yesterday afternoon. No crash so far.
Very encouraging.

**Comment by mliszcz** [comment]
Hi @lorenzopivetta and @gscalamera - any news from the test run?

@bourtemb or @Ingvord - I think that at least one of you needs to review this the PR before it can be merged. There is also a backport #665, quite similar to this PR so you can have a look as well.

**Comment by gscalamera** [comment]
> Hi @lorenzopivetta and @gscalamera - any news from the test run?
> 
> @bourtemb or @Ingvord - I think that at least one of you needs to review this the PR before it can be merged. There is also a backport #665, quite similar to this PR so you can have a look as well.


Running since almost 24 hours without any issue. I would say it's OK.

**Comment by mliszcz** [comment]
Two approvals, no complains so I'll merge the PR. Thanks to everyone involved in the review and testing!

**Pull request merged**
