### PR TITLE
Tango 9 can again be built with older compilers

### PR DESCRIPTION
**Pull request by bourtemb**
(Tested with gcc 3.4.6 and gcc 4.4.5)

### CODE REVIEW

**Comment by bourtemb** [comment]
I agree with you @t-b. We should try to set up Travis to compile with older compilers in order to avoid to introduce again some C++ 11 code which is not supported by these old compilers.

**Comment by bourtemb** [comment]
This does not mean we cannot put any C++ 11 code in Tango 9 LTS. If we put C++ 11 code, it should be surrounded by some #ifdef directives and an alternative code for older compilers should be there too.

**Comment by andygotz** [comment]
Thanks for reactivating this option again. I have been thinking about supporting old compilers and after checking I found that gcc 3.4 was released in 2006 while gcc 4.4 was released in 2010. I wonder how long we need to support these compilers? The first version of gcc which supported C++11 was gcc 4.7 which was released in 2012. We plan to support LTS-9 for another 5 years at least. Would it not be reasonable to say we need C++11 support at some point? It will simplify the code and the development.

**Comment by bourtemb** [comment]
I just wanted to check how difficult it would be to support these compilers again...
It appeared it was not too difficult so I did the job ;-) ...
Of course, supporting them will generate more work on our side, especially when including changes coming from Tango 10 development branch (master branch) into Tango 9 LTS.

**Comment by t-b** [comment]
@andygotz 

> The first version of gcc which supported C++11 was gcc 4.7 which was released in 2012. 

Using gcc 4.7 with C++11 is no fun. According to https://gcc.gnu.org/projects/cxx-status.html#cxx11 one should at least use 4.8. From my experience it starts to get usable with 4.9 (mainly due to STL issues in earlier versions).

**Pull request merged**
