### PR TITLE
Backport fix 675 no archive periodic events after polling restart

### LINKED ISSUE #675: Archive periodic events no longer received after attribute polling restart
Archive periodic events are no longer sent by the device server if the remote attribute polling is temporary stopped and restarted, archive events based on archive change event thresholds are still sent. It seems like there is no issue with standard PERIODIC events (not archive periodic events).

Here is how you can reproduce the issue with TangoTest device server for instance.

1. Start Tango Test device
2. Set the polling period to 1000 ms on ampli attribute
3. Configure the archive event properties for the ampli attribute with an archive absolute change threshold of 1, and archive period of 3000
4. Start a Tango client (or more) which subscribes to sys/tg_test/1/ampli attribute archive events
5. At this point, the clients receive archive events as expected (every 3s)
6. Stop the polling for ampli attribute
7. The clients receive an API_PollObjNotFound error event
8. Restart the polling for ampli attribute (set to 3000ms for instance)
9. The clients receive 1 archive event for ampli attribute.
10. Wait for some time longer than the archive period event configuration for ampli attribute
11. The archive periodic events are no longer received by the clients/sent by the server after this single event.
12. Set ampli attribute to a different value which should trigger archive change event
13. The clients receive the archive event triggered by the change but the archive periodic events are still not received.

Restarting the device server restores a correct behaviour. Restarting the device sys/tg_test/1 (restart device from jive or DevRestart('sys/tg_test/1') on TangoTest admin device as well as RestartServer command on TangoTest admin device) seems to solve the issue too at some point.

I tested with tango-9-lts branch and 9.3-backports branch, as well with 9.3.3 and the bug seems to be present in all these versions

### LINKED ISSUE #774: Backport for #704
https://github.com/tango-controls/cppTango/pull/704

### PR DESCRIPTION
**Pull request by mliszcz**
Backport of #704.
Fixes #774. Fixes #675.

### CODE REVIEW

**Comment by t-b** [comment]
According to https://github.com/tango-controls/cppTango/commits/9.3-backports the archive events commit is already part of 9.3-backports. This looks like a error from my side. Should I revert it?

**Comment by mliszcz** [comment]
@t-b I didn't know (or remember) that it was already backported, sorry! I suggest to keep this PR open until we figure out why tests are failing in all jobs:
```
The following tests FAILED:
	  9 - CXX::cxx_class_dev_signal (Failed)
	 10 - CXX::cxx_class_signal (Failed)
	 21 - CXX::cxx_signal (Failed)
	 29 - CXX::cxx_enum_att (Failed)
	 31 - CXX::cxx_fwd_att (Failed)
```
I'll have a look before the meeting on Thursday.
Also, please do not bother with reverting the commit that we already have in 9.3-backports if you are not planning to release that branch right now and if it is not breaking anything.

**Comment by mliszcz** [comment]
I did two changes:
* rebased the PR on top of 9.3-backports, as a result the commit with the correction disappeared from the PR, probably because it was already backported by Thomas,
* corrected the test to do proper clean-up. In the Kernel Meeting Anton suggested that there the new test may interfere with the old tests and it turns out he was right. I totally forgot that we are not restarting the database containers between tests in the 9.3-backports branch.

**Comment by t-b** [comment]
@mliszcz Thanks. I'm merging this now.

**Pull request merged**
